<a href="https://colab.research.google.com/github/sowrab9949/Mini-Project-on-Image-classification/blob/master/Mini_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
! pip install bing-image-downloader

In [ ]:
! pip install plotly==4.5.2

     |████████████████████████████████| 7.1MB 2.3MB/s 
  Found existing installation: plotly 4.4.1
    Uninstalling plotly-4.4.1:
      Successfully uninstalled plotly-4.4.1


In [ ]:
cd /content/drive/My Drive/smartknower/Project image classifier

/content/drive/My Drive/smartknower/Project image classifier


In [ ]:
!mkdir pictures

mkdir: cannot create directory ‘pictures’: File exists


In [ ]:
cd pictures

/content/drive/My Drive/smartknower/Project image classifier/pictures


In [ ]:
from bing_image_downloader import downloader
downloader.download('Covid 19 N95 Masks',limit = 30,output_dir = 'pictures')



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://i.ytimg.com/vi/WHYUsdAUi1w/maxresdefault.jpg
[%] File Downloaded !

[%] Downloading Image #2 from https://media.npr.org/assets/img/2020/04/03/coronavirus-3m-masks-n95_wide-fc59461b741e300db365174612129402ec97db5f.jpg?s=1400
[%] File Downloaded !

[%] Downloading Image #3 from https://i.ebayimg.com/images/i/323369881846-0-1/s-l1000.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://thumbor.forbes.com/thumbor/fit-in/1200x0/filters%3Aformat%28jpg%29/https%3A%2F%2Fspecials-images.forbesimg.com%2Fimageserve%2F1208482559%2F0x0.jpg
[%] File Downloaded !

[%] Downloading Image #5 from https://media.blogto.com/articles/20200124-n95masks.jpg?w=2048&amp;cmd=resize_then_crop&amp;height=1365&amp;quality=70
[%] File Downloaded !

[%] Downloading Image #6 from https://news.immitate.com/wp-content/uploads/2020/03/3m-doubles-output-of-n95-respirator-masks-amid-coronavirus-outbreak-new-york-pos

In [ ]:
from bing_image_downloader import downloader
downloader.download('Cloth Mask Covid',limit = 30,output_dir = 'pictures')



[!!]Indexing page: 1

[%] Indexed 30 Images on Page 1.


[%] Downloading Image #1 from https://www.gannett-cdn.com/presto/2020/03/24/PLSJ/aa9fed4b-2751-4d80-94af-c2f302c4696a-Clothmask_ClaireWhite_Charlotte.jpg?crop=959,540,x0,y36&amp;width=1600&amp;height=800&amp;fit=bounds
[%] File Downloaded !

[%] Downloading Image #2 from https://filipinotimes.net/wp-content/uploads/2020/04/cloth-masks.jpg
[%] File Downloaded !

[%] Downloading Image #3 from https://www.wsbtv.com/resizer/wNkK_4OocbbFjd2f28HV-fhDM-w=/1200x675/arc-anglerfish-arc2-prod-cmg.s3.amazonaws.com/public/5ALCGGVTFRHKBKLODBSX77L4UU.jpg
[%] File Downloaded !

[%] Downloading Image #4 from https://media.ktvb.com/assets/KGW/images/f886f792-7516-49e5-a537-4ca2231c7815/f886f792-7516-49e5-a537-4ca2231c7815_1920x1080.png
[%] File Downloaded !

[%] Downloading Image #5 from https://www.gannett-cdn.com/presto/2020/03/24/PLSJ/24e54a88-d1f9-495d-8f77-395b9c85a377-Clothmask_TaylorMay_Portland.jpg?width=540&amp;height=&amp;fit=bounds&am

In [10]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from skimage.io import imread
from skimage.transform import resize 
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [11]:
# Reshaping and flattening of data
out_pic = []
flat_pic = []
pic = []
path = '/content/drive/My Drive/smartknower/Project image classifier/pictures/pictures/'
for dirpath, dirnames, filenames in os.walk(path):
  for files in filenames:
    dis = dirpath.split('/')[-1]
    out_pic.append(dis)
    img = imread(f'{path}{dis}/{files}')
    re_pic = resize(img,(100,100,3))
    flat_pic.append(re_pic.flatten())
    pic.append(re_pic)
flat_pic = np.array(flat_pic)
out_pic = np.array(out_pic)
pic= np.array(pic)


In [12]:
print(flat_pic)

[[0.92627451 0.92627451 0.93411765 ... 0.97215686 0.96431373 0.98823529]
 [0.00392157 0.00784314 0.01176471 ... 0.24705882 0.26666667 0.27843137]
 [1.         1.         1.         ... 1.         1.         1.        ]
 ...
 [0.6429902  0.63137255 0.65882353 ... 0.52941176 0.52941176 0.52156863]
 [0.61568627 0.51764706 0.39607843 ... 0.7254902  0.65490196 0.55686275]
 [0.3751634  0.1727451  0.84581699 ... 0.48369281 0.13921569 0.8372549 ]]


In [13]:
#Creating DataFrame
df = pd.DataFrame(flat_pic)
df['Output'] = out_pic
df.head()

0         1         2  ...     29998     29999              Output
0  0.926275  0.926275  0.934118  ...  0.964314  0.988235  Covid 19 N95 Masks
1  0.003922  0.007843  0.011765  ...  0.266667  0.278431  Covid 19 N95 Masks
2  1.000000  1.000000  1.000000  ...  1.000000  1.000000  Covid 19 N95 Masks
3  0.741176  0.709804  0.756863  ...  0.643137  0.690196  Covid 19 N95 Masks
4  0.028394  0.000000  0.027451  ...  0.000000  0.062745  Covid 19 N95 Masks

[5 rows x 30001 columns]

In [14]:

df['Output'].nunique()

2

In [15]:
df['Output'].value_counts()

Cloth Mask Covid      30
Covid 19 N95 Masks    30
Name: Output, dtype: int64

In [16]:
# Training and testing data.
x = df.drop('Output',axis=1).values
y = df['Output'].values

In [17]:
x_train,x_test,y_train,y_test = train_test_split(x,y,random_state = 0)

In [18]:
# Using gridsearch_cv for best param.
param= {'n_neighbors':np.arange(1,48)}
model = KNeighborsClassifier()
model_cv = GridSearchCV(model,param)
model_cv.fit(x,y)

GridSearchCV(cv=None, error_score=nan,
             estimator=KNeighborsClassifier(algorithm='auto', leaf_size=30,
                                            metric='minkowski',
                                            metric_params=None, n_jobs=None,
                                            n_neighbors=5, p=2,
                                            weights='uniform'),
             iid='deprecated', n_jobs=None,
             param_grid={'n_neighbors': array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47])},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [19]:
model_cv.best_params_

{'n_neighbors': 23}

In [20]:
model = KNeighborsClassifier(n_neighbors=23)
model.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=23, p=2,
                     weights='uniform')

In [21]:
y_pred= model.predict(x_test)
y_pred

array(['Cloth Mask Covid', 'Cloth Mask Covid', 'Cloth Mask Covid',
       'Covid 19 N95 Masks', 'Covid 19 N95 Masks', 'Covid 19 N95 Masks',
       'Cloth Mask Covid', 'Cloth Mask Covid', 'Cloth Mask Covid',
       'Covid 19 N95 Masks', 'Cloth Mask Covid', 'Covid 19 N95 Masks',
       'Cloth Mask Covid', 'Covid 19 N95 Masks', 'Cloth Mask Covid'],
      dtype=object)

In [22]:
y_test

array(['Covid 19 N95 Masks', 'Cloth Mask Covid', 'Cloth Mask Covid',
       'Covid 19 N95 Masks', 'Covid 19 N95 Masks', 'Covid 19 N95 Masks',
       'Cloth Mask Covid', 'Cloth Mask Covid', 'Cloth Mask Covid',
       'Covid 19 N95 Masks', 'Covid 19 N95 Masks', 'Covid 19 N95 Masks',
       'Cloth Mask Covid', 'Cloth Mask Covid', 'Cloth Mask Covid'],
      dtype=object)

In [23]:
# Evaluating the model.
accuracy_score(y_test,y_pred)

0.8

In [24]:
confusion_matrix(y_test,y_pred)

array([[7, 1],
       [2, 5]])

In [25]:
pd.crosstab(y_test,y_pred, rownames=['Actual'], colnames=['Predicted'], margins=True)

Predicted           Cloth Mask Covid  Covid 19 N95 Masks  All
Actual                                                       
Cloth Mask Covid                   7                   1    8
Covid 19 N95 Masks                 2                   5    7
All                                9                   6   15

In [26]:
print(classification_report(y_test,y_pred))

                    precision    recall  f1-score   support

  Cloth Mask Covid       0.78      0.88      0.82         8
Covid 19 N95 Masks       0.83      0.71      0.77         7

          accuracy                           0.80        15
         macro avg       0.81      0.79      0.80        15
      weighted avg       0.80      0.80      0.80        15



In [27]:
#Predicting for any new image
fl = []
i = imread('https://assets.bigcartel.com/product_images/257615057/mautto-cloth-face-covering-patterns-sm.jpg?auto=format&amp;fit=max&amp;w=2000')
re= resize(i,(100,100,3))
fl.append(re.flatten())
fl = np.array(fl)
y_pred = model.predict(fl)
y_pred
